### ISSUE TITLE
Can't get the Scan SBOM / Upload SBOM features in the UI to work

### ISSUE THREAD

**Issue by chmeliik** [trustification/trustification#1151]
When trying out the Scan SBOM functionality in https://trustification.dev/scanner (and Upload SBOM in a private deployment), the UI keeps returning the same error regardless of the SBOM content: `Failed to parse SBOM as CycloneDX 1.3: Unsupported packages detected. Supported packages: 'maven', 'gradle', 'npm', 'gomodules', 'pip'`

![image](https://github.com/trustification/trustification/assets/38193343/e5c4f367-57c1-4b60-82c8-ab5925f33a9a)

I have tried with the following CycloneDX 1.3 SBOMs:

completely empty 

```json
{
  "bomFormat": "CycloneDX",
  "specVersion": "1.3",
  "version": 1
}
```

a dummy SBOM with one pip component and a metadata.component

```json
{
  "bomFormat": "CycloneDX",
  "specVersion": "1.3",
  "version": 1,
  "metadata": {
    "component": {
      "type": "application",
      "name": "my-app",
      "version": "0.1.0",
      "purl": "pkg:pypi/my-app@0.1.0"
    }
  },
  "components": [
    {
      "type": "library",
      "name": "requests",
      "version": "2.31.0",
      "purl": "pkg:pypi/requests@2.31.0"
    }
  ]
}
```

an SBOM generated by Syft for its own codebase - [sbom-syft.json](https://github.com/trustification/trustification/files/14493269/sbom-syft.json)

The error message is the same in all cases

**Comment by ctron** [comment]
It is unsupported because of limitations of the scanner backend (CRDA). However, we did relax that requirement for the upload process (vs scan). So you can upload those now, given a more recent version.

**Comment by chmeliik** [comment]
> However, we did relax that requirement for the upload process (vs scan). So you can upload those now, given a more recent version.

Perfect, that addresses my concerns :+1: 

Which version specifically contains those changes?

**Comment by ctron** [comment]
I am not sure @carlosthe19916  might now. But I would say everything that's on `main` or `release/1.0.z`.

**Comment by carlosthe19916** [comment]
Yes, the fix has been applied only a few hours ago and it is inside the `main` and `release/1.0.z` branch.

**Comment by chmeliik** [comment]
Ack, thanks!
