### ISSUE TITLE
[TC Console.dot Portal] - The packages landing page has an error and no data can be displayed

### ISSUE THREAD

**Issue by ikanias** [trustification/trustification#119]
Description
The packages landing page has an error and no data can be displayed.

Steps to reproduce:

Open the console portal
Select the 'Packages' option in the left menu
Expected result:
There results should be displayed properly if the package was found or a proper message should be displayed if there was no package found.

Actual result:
There is a 500 server error without entering anything in the search, and when trying to click on 'From Package URL' button
**JIRA ticket for reference: https://issues.redhat.com/browse/TC-191

![error 500_1](https://github.com/trustification/trustification/assets/69799772/5c2cf705-0838-45d5-ad86-dd0130313ad9)
![error 500_2](https://github.com/trustification/trustification/assets/69799772/1bb98eab-544e-4b71-8838-bd88a5f795f7)

**Comment by lulf** [comment]
This should work again now. At the moment there is little package data ingested, but that is bound to change soon. For now I've manually ingested the SBOMs in the bombastic/testdata.

**Comment by ikanias** [comment]
Hey thanks! Looks much better now.
