### ISSUE TITLE
[TC Console.dot Portal] - In 'Packages' option filter, when selecting a filter category, there is an 'X' icon even if the there is no text

### ISSUE THREAD

**Issue by ikanias** [trustification/trustification#120]
Description
In 'Packages' option filter, when selecting a filter category, there is an 'X' icon even if the there is no text.

Steps to reproduce:

Open the console portal
Select the 'Packages' option
Select a filter type which is not displayed in the filter breadcrumbs and leave the filter text box empty
Expected result:
The text box of the filter should not contain an 'X' button (At least not an enabled one) until a text is actually inserted in the text box

Actual result:
Even when no text is inserted in the filter text box, there is still an 'X' button enabled which has no purpose

**JIRA ticket for reference: https://issues.redhat.com/browse/TC-192

![Unnecesary X button](https://github.com/trustification/trustification/assets/69799772/7ff1878b-2364-465a-b52d-6ff95e893a38)

**Comment by ikanias** [comment]
This is still happening...

**Comment by lulf** [comment]
Now this is fixed

**Comment by ikanias** [comment]
Verified.
