### ISSUE TITLE
[TC Console.dot Portal] - When selecting 'Packages' option on the left menu, it is not possible to load results for the default filter

### ISSUE THREAD

**Issue by ikanias** [trustification/trustification#121]
Description
When selecting 'Packages' option on the left menu, it is not possible to load results for the default filter.

Steps to reproduce:

open the console portal
Go to Packages option in the menu
Click on the '-->' button to the right side of the filter text box
Expected result:
The results for the default filter of 'Type'=maven and 'Name'=quarkus-core should be loaded and displayed

Actual result:
No results are displayed when clicking the '-->' button. When checked the Network tab in developer options in Chrome options, no request is sent to the server when clicking on this button.

**JIRA ticket for reference: https://issues.redhat.com/browse/TC-193

Attached video:
[No response in default filter.zip](https://github.com/trustification/trustification/files/11715111/No.response.in.default.filter.zip)

**Comment by lulf** [comment]
This should be fixed now since the search UI does not show these filters.

**Comment by ikanias** [comment]
This is still happening...

**Comment by lulf** [comment]
This is fixed now. By default a query matching all documents is run (and first 10 results fetched)

**Comment by ikanias** [comment]
Verified.
