### ISSUE TITLE
[TC Console.dot Portal] - In the 'Advisories' and 'Vulnerabilities' sections, there are no search results found no matter what string is inserted

### ISSUE THREAD

**Issue by ikanias** [trustification/trustification#126]
Description
In the 'Advisories' or the 'Vulnerabilities' section, there are no search results found no matter what string is inserted

Steps to reproduce:

Open console portal
Select the 'Advisories'/'Vulnerabilities option
Insert any string in the search box -> Click '->' button
Expected result:
There will be results displayed according to the search strings inserted

Actual result:
No results are displayed, no matter what string is inserted.

![No_adv](https://github.com/trustification/trustification/assets/69799772/661cd6e1-8024-400b-ba6f-eec0d1a8b89e)
![No_vulns](https://github.com/trustification/trustification/assets/69799772/52d6e2f6-bf0f-4284-86ea-804a101b2ef2)

**Comment by lulf** [comment]
Should be fixed now

**Comment by ikanias** [comment]
Verified and it is working well now.

**Comment by ikanias** [comment]
Verified and it is working well now.
