### ISSUE TITLE
[TC Console.dot Portal] - In the 'Packages' page, when there is only one page with results, the paging shows there are 2 pages

### ISSUE THREAD

**Issue by ikanias** [trustification/trustification#144]
Description
In the 'Packages' page, when there is only one page with results, the paging shows there are 2 pages.

Steps to reproduce:

Open the console portal
Select the 'Packages' page
Search for 'nodejs' -> Click '->' button
Check paging controls
Expected result:
There is only one page with 3 results so the paging controls should display: 1 of 1 and the '>' and '>>' buttons should be disabled

Actual result:
There is only one page with 3 results and the paging controls show 1 of 2 with '>' button enabled, and when clicking on it, it shows 2 of 1.

JIRA ticket for reference: https://issues.redhat.com/browse/TC-226 

![wrong number of pages](https://github.com/trustification/trustification/assets/69799772/e0a0ba3e-4e32-4392-a1b0-7ba7fdaf8fd9)

**Comment by lulf** [comment]
Fixed
