### ISSUE TITLE
[TC Console.dot Portal] - When trying to download a related SBOM of a package, there is an error displayed

### ISSUE THREAD

**Issue by ikanias** [trustification/trustification#146]
Description
[TC Console.dot Portal] - When trying to download a related SBOM of a package, there is an error displayed.

Steps to reproduce:

Open the console portal
Search for 'io' and Click the '-->' button
Open one of the records by clicking the '>' button on a record in the table
Click on the 'Download' button
Expected result:
The SBOM file will be downloaded properly to the local machine

Actual result:
There is an error message displayed.

JIRA ticket for reference: https://issues.redhat.com/browse/TC-235

A video is attached:
[Download SBOM issue.zip](https://github.com/trustification/trustification/files/11758679/Download.SBOM.issue.zip)

**Comment by lulf** [comment]
I'm not able to reproduce this, is it still an issue after the latest updates of trustification.dev?
