### ISSUE TITLE
UI code reusability: pagination

### ISSUE THREAD

**Issue by carlosthe19916** [trustification/trustification#152]
I saw there are some pieces of code that are repeated multiple times for Paginating tables. The following piece of code is repeated across:

- https://github.com/trustification/trustification/blob/main/spog/ui/src/components/vulnerability.rs#L110
- https://github.com/trustification/trustification/blob/main/spog/ui/src/components/vexination.rs#L98
- https://github.com/trustification/trustification/blob/main/spog/ui/src/components/advisory.rs#L105

![Screenshot from 2023-06-16 11-47-00](https://github.com/trustification/trustification/assets/2582866/7f24bcaa-1a37-4161-9e1e-76f9edeed491)

We could enhance the code and allow re-usability of certain logic common across tables.

**Comment by lulf** [comment]
Thanks for the good description! I agree, it would be nice to better reuse pagination. It could be the number of pages going up or down, but I think this common behavior is good to separate out.
