### ISSUE TITLE
Enable Helm charts to use multiarch images

### ISSUE THREAD

**Issue by dejanb** [trustification/trustification#1696]
Now that we are building multiarch images (#1359), like

https://github.com/trustification/trustification/pkgs/container/trust/255853592?tag=24c355f6f1f70df574aa66aa96ea7a1035e89da9

we need to modify and test helm charts to be able to deploy to both architectures.

**Comment by bxf12315** [comment]
My testing steps：
1 My minikube env is arm64.`docker version --format '{{.Server.Arch}}'
arm64`
2 helm install
3 check trust image's sha256.
docker inspect ghcr.io/trustification/trust:24c355f6f1f70df574aa66aa96ea7a1035e89da9 --format '{{index .RepoDigests 0}}'
ghcr.io/trustification/trust@sha256:cf4ee364d4689cdfec12b2de233a0d944b6bd5ff0197f8b22ed52b72e991fb73

I think this result meets our expectations.

**Comment by dejanb** [comment]
Thanks for testing and confirmation. Can you please update the charts to use this latest version of the image (similar to https://github.com/trustification/trustification/commit/f69ff5502ec4b7c33fdb9bfda853cc0df57d47bf)?
