### ISSUE TITLE
searching for dates

### ISSUE THREAD

**Issue by ctron** [trustification/trustification#176]
searching for `created:2023-06-23` turns up nothing, as that resolves into the full timestamp (with zero hour, minute, …). And by default will only find which matches that exact second.

I think we should change this into searching for "date" only. Ignoring the time.

**Comment by lulf** [comment]
Agreed, I doubt anyone need any finer granularity than date

**Comment by lulf** [comment]
Fix:

* For exact queries, strip away anything finer granularity than the date, and make a range query for start of day to end of day.
