### ISSUE TITLE
bombastic search expectations

### ISSUE THREAD

**Issue by ctron** [trustification/trustification#178]
I am having a hard time searching bombastic, here are some expectations I would have towards search:

* `qualifier:arch:s390` – turns up all SBOMs having a PURL with classifier/qualifier `arch=s390`
* `is:container` – turn up container images
* `namespace:oci` – turn up SBOms having a PURL with namespace `rpm`

**Comment by lulf** [comment]
Is this with or without https://github.com/trustification/trustification/pull/175 ?

**Comment by lulf** [comment]
I think for every unexpected behavior it would be great if we can have 1) the exact query you are using and 2) an example document you expect to match.

That would make it easy to write that down in a unit test.

**Comment by lulf** [comment]
Next steps:

* Qualifiers => index the whole key=value into a new field in the index. Keep index of values
* is:container => Current SBOM data doesn't have the classifier
* namespace:oci => this works as expected

**Comment by lulf** [comment]
Fixed?

**Comment by ctron** [comment]
Fixed!
