### ISSUE TITLE
Version information is missing

### ISSUE THREAD

**Issue by lulf** [trustification/trustification#196]
For the UI, the git version displays the suffix '-dirty'.

For the backend, it displays "VERGEN_IDEMPOTENT_OUTPUT"

![bilde](https://github.com/trustification/trustification/assets/19670/61ac36b7-aa8b-4679-a146-c23db3843bdf)

**Comment by ctron** [comment]
Is that on the deployed version?

**Comment by lulf** [comment]
Yes, it's from https://staging.trustification.dev/

**Comment by ctron** [comment]
Closed on staging:

![image](https://github.com/trustification/trustification/assets/202474/36c96e81-9041-41af-98a8-29ab11aea59f)

It is still "dirty", as that is what it is.
