### ISSUE TITLE
[Bombastic] API service

### ISSUE THREAD

**Issue by lulf** [trustification/trustification#2]
The API service is the entry point for producers and consumers of the service. The process uses the authentication service to authenticate and authorize users.

The API may be implemented using serverless functions running on KNative in order to scale with the demand. 

Should use the storage facade to talk to s3. Should use seedwing to check input.

The following REST APIs will be implemented:

* PUT /api/v1/sbom/:name - create or update an SBOM
   * Response: 200 Ok if SBOM was updated
   * Response: 404 Not found if SBOM does not exist
   * Response: 401 Unauthorized  if not authorized

* GET /api/v1/sbom/:name  - retrieve an SBOM with the given name
   * Response: 200 Ok + SBOM matching name
   * Response: 401 Unauthorized  if not authorized
   * Response: 404 Not found if SBOM does not exist

* GET /api/v1/sbom?purl=... - retrieve an SBOM for a given package URL.
   * Response: 200 Ok + SBOM matching pURL
   * Response: 401 Unauthorized  if not authorized
   * Response: 404 Not found if SBOM does not exist

* GET /api/v1/sbom?sha256=... - retrieve an SBOM for an artifact with the given sha256 hash
   * Response: same as above

* DELETE /api/v1/sbom/:name - delete an SBOM for artifact with name
   * Response: 200 Ok if SBOM was deleted
   * Response: 404 Not found if SBOM does not exist
   * Response: 401 Unauthorized  if not authorized

* DELETE /api/v1/sbom?purl=... - delete an SBOM for artifact with pURL
   * Response: 200 Ok if SBOM was deleted
   * Response: 404 Not found if SBOM does not exist
   * Response: 401 Unauthorized  if not authorized

* DELETE /api/v1/sbom?sha256=... - delete an SBOM for artifact with hash
   * Same as above

**Comment by jcrossley3** [comment]
This is in progress already, right? We can already GET/PUT SBOM's.

**Comment by lulf** [comment]
I've only added the minimum PUT/GET for now. This is started, but definitely needs work, and is not something I'm actively working until I have ironed some quirks in the storage and indexing.

**Comment by lulf** [comment]
I think the API is complete now?
