### ISSUE TITLE
Users shouldn't have to quote search strings that contain colons

### ISSUE THREAD

**Issue by jcrossley3** [trustification/trustification#218]
...or any other special character used by our search library of choice. It makes for a bad user experience.

If we're using github's search as a model, then we should make a best effort to search for what the user enters and only fail if nothing is found. When I search in the trustification repo for `self:` or `self::spdx`, github returns me all sorts of useful matches. It's only when I search for `self:foo` that github gently suggests that my qualifier may be wrong. That's a much nicer user experience, imo.

**Comment by lulf** [comment]
This might relate to how the query is parsed in https://github.com/ctron/sikula

**Comment by ctron** [comment]
There is definitely room for improvement. A first step was to parse the query in the frontend as the user types. But yes, we could also be more forgiving/ignorant/tolerant to things like this.

The biggest question to me in such cases is, what is the expected outcome? And I think as long that is defined and consistent (as "good" as the rest) that shouldn't be a big deal.

**Comment by lulf** [comment]
Is this closeable with the simple query language?
