### ISSUE TITLE
Broken api calls on swagger UI

### ISSUE THREAD

**Issue by mrrajan** [trustification/trustification#231]
JIRA - https://issues.redhat.com/browse/TC-307
On Swagger UI, Some of the API requests has been broken and they are failing while execution.

- SPOG API: https://api.trustification.dev/swagger-ui/
Error `"Resolver error at paths./api/v1/advisory.get.responses.200.content.application/json.schema.$ref Could not resolve reference: Could not resolve pointer: /components/schemas/Csaf does not exist in document"` Occurs while accessing the end points
![Screenshot from 2023-07-04 19-54-53](https://github.com/trustification/trustification/assets/86094767/a4fab285-5079-4a02-b891-3c5a50aa3e5b)

- Below End points loaded with error either Query deserialize error: missing field `id` or Query deserialize error: missing field `q` 
          - /api/v1/advisory
          - /api/v1/advisory/search
          - /api/v1/package
          - /api/v1/package/search

**Comment by lulf** [comment]
Consider spog api internal for the console.
