### ISSUE TITLE
Startup of guac with compose fails

### ISSUE THREAD

**Issue by ctron** [trustification/trustification#264]
starting up the `compose-guac.yaml` fails to start up `nats`, with a `permission denied` on the config file.

The reasons is the missing SElinux label which can be added when mounting by appending the `:z` operation:

```yaml
    volumes:
      - ./container_files/nats:/config/nats:z
```

Not sure if that breaks stuff of others, but makes it work with podman.

**Comment by lulf** [comment]
@dejanb Fixed?

**Comment by ctron** [comment]
Works for me for a while. I would close it an re-open when necessary.
