### ISSUE TITLE
Broken Links on Trustification Documentation

### ISSUE THREAD

**Issue by mrrajan** [trustification/trustification#265]
On Trustification documentation - https://docs.trustification.dev/trustification/user/retrieve.html links are broken 

- Vexination API Examples second link - https://docs.trustification.dev/trustification/user/retrieve.html#_vexination_api
![Screenshot from 2023-07-10 17-00-48](https://github.com/trustification/trustification/assets/86094767/47de8a02-45ca-4b14-b0c2-631b20b93a57)

- All Example section links - https://docs.trustification.dev/trustification/user/retrieve.html#_examples
![Screenshot from 2023-07-10 17-00-54](https://github.com/trustification/trustification/assets/86094767/5e1a18df-c6ba-40c5-bcc7-90d02a262b80)

**Comment by lulf** [comment]
Should be fixed in #399
