### ISSUE TITLE
Max payload exceeded error on compose-walkers.yaml

### ISSUE THREAD

**Issue by mrrajan** [trustification/trustification#267]
While running compose-walkers.yaml file "maximum payload exceeded" error occurs.
![Screenshot from 2023-07-10 16-00-36](https://github.com/trustification/trustification/assets/86094767/5b5376ce-8315-463c-bbfd-42fac1fbaab5)
JIRA - https://issues.redhat.com/browse/TC-312

**Comment by jcrossley3** [comment]
Do you have any steps to reproduce? Any particular file that causes it?

Please include the value of TRUST_VERSION when reporting issues against any of the compose scripts, thanks!

**Comment by jcrossley3** [comment]
FWIW, I was unable to reproduce with 0.1.0-nightly.7c99b254

**Comment by mrrajan** [comment]
Hi @jcrossley3, I could reproduce this issue with - v0.1.0-nightly.21ccb9a2-dirty. I have added `:z` on the volumes section of compose-guac.yaml and executed the command `podman-compose -f compose-guac.yaml up`
![Screenshot from 2023-07-21 11-23-15](https://github.com/trustification/trustification/assets/86094767/68a7ae3e-acf0-4446-8551-299f1c7d6da2)

**Comment by ctron** [comment]
I ran into the same issues, I had to raise the limit to 1GiB IIRC … the changed I had to apply to get guac running are here: https://github.com/trustification/trustification/pull/268/files

**Comment by mrrajan** [comment]
I copied the contents from PR #268 and the issue is not occurred.

**Comment by lulf** [comment]
Fix was merged in https://github.com/trustification/trustification/pull/268
