### ISSUE TITLE
Pagination shows incorrect values when the user modifies no of rows per page

### ISSUE THREAD

**Issue by mrrajan** [trustification/trustification#278]
When the user Navigates to end of the page and modifies the no of rows per page count, then application loads with incorrect page count and "No results" found message on the screen.

Expected Result:

- No of Pages should appear based on total no of items and rows per page
- At any point of time, if the user modifies rows per page count - the total page count should rendered appropriately
- If the user is on out of the limit for selected row per page count, then the user should be taken to last page. For example,consider there are 59 rows available with 10 per page config and the user is on 5th page. When the user selects 25 rows per page, then the user should be taken to 3rd page with 9 rows populated and if the user selects 50 rows per page, then he should be taken to 2nd page.
- The user should not be allowed to manually enter page index value more than total no of pages on page index text box.

JIRA - https://issues.redhat.com/browse/TC-334

**Comment by ctron** [comment]
@mrrajan there's a PR waiting which should contain the fix. It would be cool if you could do some preliminary testing on it to see if this matches your expectations.

**Comment by mrrajan** [comment]
Sure @ctron I will take a look!

**Comment by mrrajan** [comment]
Verified with #281 preview - http://trustification-spog-pr-281-preview.surge.sh/ working as expected.
[Screencast from 2023-07-14 12-50-17.webm](https://github.com/trustification/trustification/assets/86094767/a03cd0a7-36e8-4fba-bc57-10c3319e07d1)
