### ISSUE TITLE
Probably missing info on spog readme.md ?

### ISSUE THREAD

**Issue by helio-frota** [trustification/trustification#294]
hi 

Everything builds and installs etc :+1: 

But when I try to access the page I got this chicken :chicken: 

![2023-07-18_09-15](https://github.com/trustification/trustification/assets/6443576/6df59fda-6504-4f70-8ccb-bd88dee0c2dd)

https://github.com/trustification/trustification/tree/main/spog/ui#setting-up

thanks

**Comment by ctron** [comment]
Yes, that's missing a pointer to the main "developing" file, setting up the rest of the system
