### ISSUE TITLE
Seeing token error when loading console

### ISSUE THREAD

**Issue by lulf** [trustification/trustification#336]
Sometimes I'm getting this error when I load the console:

<img width="1032" alt="image" src="https://github.com/trustification/trustification/assets/19670/d781d457-78f7-47f5-b409-468fc3361467">

What's especially strange is that 'ctron' is mentioned which is a different user to mine.

**Comment by ctron** [comment]
@lulf did you see this again?

**Comment by lulf** [comment]
I havent for a long time ,.feel free to close
