### ISSUE TITLE
Some documents return 404

### ISSUE THREAD

**Issue by ctron** [trustification/trustification#349]
I had this now a few times, a search returns hits, but then, fetching the document, it returns 404:

![image](https://github.com/trustification/trustification/assets/202474/b793f1cc-9b37-4faa-8b2f-224ec60551de)

--- 

JIRA: https://issues.redhat.com/browse/TC-373

**Comment by i386x** [comment]
@ctron Do you have some hints how to reproduce this?

**Comment by ctron** [comment]
Ah, I think that's actually been closed. IIRC it was an issue with deleting object, but not having them deleted in the index. Which should work for a while now. And I never saw this again.

I would say, let's close it.
