### ISSUE TITLE
SBOM POST call with Empty input panicked

### ISSUE THREAD

**Issue by ctron** [trustification/trustification#352]
When the user uploads an Empty file using SBOM API Post call, the application panicked and throws error.

Expecting system to throw 400 response code, instead the system panicked with error

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error("EOF while parsing a value", line: 1, column: 0)', integration-tests/tests/bombastic.rs:220:77
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'test_upload_empty_sbom' panicked at 'explicit panic', integration-tests/tests/bombastic.rs:218:1
```

---

JIRA: https://issues.redhat.com/browse/TC-361

**Comment by lulf** [comment]
Test error

**Comment by mrrajan** [comment]
@lulf @ctron I have tested the fix with the script https://github.com/trustification/trustification/blob/a70d23716a0b2b480035663aaffe92f56f036cb2/integration-tests/tests/bombastic.rs#L347 I am still getting the same response
![Screenshot from 2023-09-12 16-45-29](https://github.com/trustification/trustification/assets/86094767/012e5fb0-025d-4e6d-8b9a-c77c536059b1)
