### ISSUE TITLE
Affirm that correct event is fired for invalid SBOM

### ISSUE THREAD

**Issue by jcrossley3** [trustification/trustification#363]
Related to #7

This is a tricky one, because we don't validate the content of the SBOM on the upload. To mitigate the risk of a DoS attack, we avoid loading the entire SBOM into memory -- we stream chunks directly to S3, and the indexer serially loads (and validates, eventually) them once notified that all the chunks have been streamed successfully.

I guess we have to decide if this test is worth the additional code complexity to "peek" at the payload to see if it's small enough to validate. Any thoughts @lulf?

_Originally posted by @jcrossley3 in https://github.com/trustification/trustification/pull/356#discussion_r1287388376_

**Comment by lulf** [comment]
I think avoiding loading the SBOM into memory is important, though maybe less so assuming we trust any authenticated user. Perhaps an option would be to rely on the indexer posting 'failed to parse' events, which it currently does, to the sbom-failed topic?

The test could then consume from that topic to verify that the invalid document gets the correct treatment.

**Comment by ikanias** [comment]
Relevant JIRA ticket: https://issues.redhat.com/browse/TC-385
