### ISSUE TITLE
[Trustification][SPOG][UI]Home page Search fields loads all the data for the first time

### ISSUE THREAD

**Issue by mrrajan** [trustification/trustification#386]
On Trustification home page, when the user tries to search for an SBOM or advisory - the application loads all the data instead of filtering the given input.
This happens only for the first time and when the user navigates back to the home page from the search result and perform the same search, the results are loaded as expected.
Steps to reproduce:

1. Open a private/incognito window or clear cache
2. Navigate to trustification application
3. On Home screen, enter "amq" on the "Search for an SBOM or advisory" text box
4. Click on "Search" button
5. Application will navigate to "Search Result" page with all the SBOM and advisory information

Attached image for reference, where the API call is made for empty query and `amq` subsequently to retrieve all the information.

![Screenshot from 2023-08-11 17-21-47](https://github.com/trustification/trustification/assets/86094767/09ec343f-856c-490c-b85a-b9f161b4c32a)

Image version - v0.1.0-nightly.2f94c33f-dirty
Environment - https://trustification.dev/
JIRA# https://issues.redhat.com/browse/TC-378

**Comment by danbev** [comment]
I've tried to reproduce this issue but I've not been able to so far. 
Following the instructions listed above below is a screen shot of what I see:

![image](https://github.com/trustification/trustification/assets/432351/d5da0668-d719-46d4-83d9-5f13fa0de36d)

This looks like what I'd expect with the result entries all look related to `amq`. Is there something I'm missing or could this perhaps we been fixed already?

**Comment by mrrajan** [comment]
@danbev Interesting, I could reproduce this error on SBOM tab. 
But on the advisories tab this is inconsistent. On 3 out of 5 tries, I could reproduce the issue on Advisory tab.
At the screenshot you have attached the SBOM count pointed to 207, where as there are only 6 SBOMs matching for the filtering condition.
I have added comments and screen recording on the JIRA - https://issues.redhat.com/browse/TC-378

**Comment by danbev** [comment]
@mrrajan Sorry, I was looking at the list of results and not at the counts. Thanks for the screen recording, I'll take another look at this now.
