### ISSUE TITLE
`--authentication-disabled` seems to have no effect

### ISSUE THREAD

**Issue by jcrossley3** [trustification/trustification#387]
Steps to reproduce:

```
cargo run -p trust -- bombastic api --devmode -p 8082 &
curl -i --json @bombastic/testdata/my-sbom.json http://localhost:8082/api/v1/sbom?id=my-sbom
```
I get a 201. I'd expect a 401 without the `--authentication-disabled` switch.

**Comment by lulf** [comment]
I think it's because devmode turns off authorization. Changing the authz controls to change authz policy based on authentication-disabled instead should fix it.
