### ISSUE TITLE
Crawl SBOMs from Red Hat

### ISSUE THREAD

**Issue by lulf** [trustification/trustification#41]
Use this API to get SBOMs and ingest into bombastic https://access.redhat.com/security/data/sbom/beta/spdx/ using a process similar to the vexination-walker.

**Comment by lulf** [comment]
Apologies, I've tried to clear this up now @jbtrystram . Thanks for looking into it.

**Comment by lulf** [comment]
Fixed in #125 . @jbtrystram Should a follow-up issue be created for allowing it to run continuously picking up when things are added to changes.txt as well?

**Comment by jbtrystram** [comment]
@lulf is that what the vexination walker does ? If so, yes, they should be behaving the same

**Comment by lulf** [comment]
I don't think it does yet, but I think it should
