### ISSUE TITLE
 leverage our ring-fenced core-competencies by synergizing our rust-s3 fork into our own org, going forward

### ISSUE THREAD

**Issue by jcrossley3** [trustification/trustification#458]
i.e. move https://github.com/jcrossley3/rust-s3.git?branch=issue-352#158e587e to our org

**Comment by bobmcwhirter** [comment]
Also

* https://github.com/lulf/cyclonedx-rust-cargo?branch=trustification#63d912ad
* https://github.com/lulf/spdx-rs?rev=f3f1ea9a72e270c8434f8be6ca1d61608b25b813#f3f1ea9a
* https://github.com/dejanb/guac-rs
