### ISSUE TITLE
Advisory "revision"/"release" date

### ISSUE THREAD

**Issue by ctron** [trustification/trustification#519]
We have a column "revision" in the advisory result table. We want to sort & filter by this. The idea is to give the user "a set of recently changed documents".

Revision is actually this:

https://github.com/trustification/trustification/blob/a31c97d6a34b4e30c4d6c921a33794d3ea376208/spog/ui/src/components/advisory/mod.rs#L71

Which seems to come from this:

https://github.com/trustification/trustification/blob/a31c97d6a34b4e30c4d6c921a33794d3ea376208/spog/api/src/advisory.rs#L97

Which seems to come from this:

https://github.com/trustification/trustification/blob/a31c97d6a34b4e30c4d6c921a33794d3ea376208/vexination/index/src/lib.rs#L463

Which seems to be the "current release" date:

https://github.com/trustification/trustification/blob/a31c97d6a34b4e30c4d6c921a33794d3ea376208/vexination/index/src/lib.rs#L150-L153

However, searching by "release" brings up weird results. I assume this is due to the fact that `Release`, does a bit more:

https://github.com/trustification/trustification/blob/a31c97d6a34b4e30c4d6c921a33794d3ea376208/vexination/index/src/lib.rs#L692-L703

---

Couldn't we have a single "release" date, which carries the "last modified" date? (defaulting to the initial date if that isn't present).

**Comment by lulf** [comment]
@ctron So what I get from this is that you want the search only to search by the advisory_current rather than both advisory_current and cve_release? Maybe we can split this into two separate qualifiers instead, advisory_current and cve_release? Rather than mixing them. Then if you really want to search both one can use an OR

**Comment by ctron** [comment]
> Maybe we can split this into two separate qualifiers instead, advisory_current and cve_release? Rather than mixing them. Then if you really want to search both one can use an OR

Sounds good!
