### ISSUE TITLE
Collectorist should prune missing collectors

### ISSUE THREAD

**Issue by bobmcwhirter** [trustification/trustification#529]
When/if a collector fails, after N attempts, Collectorist should prune until the collector shows back up and reregisters.

**Comment by bobmcwhirter** [comment]
We should probably also lose the `deregister` workflow, if we can run multiple replicas behind a service, and solely work with idle pruning for unreachable.

**Comment by ctron** [comment]
I just noticed a case where it seems that shutting down one instance while firing up a new one leaves the new one unregistered, not receiving any events. Or maybe it was a case of collectorist restart.

**Comment by ctron** [comment]
Ok, here's a thought … why don't we list all the collectors explicitly in the collectorist config? That would drop a lot of complexity.
