### ISSUE TITLE
Exporter service

### ISSUE THREAD

**Issue by lulf** [trustification/trustification#6]
A process that has access to the internal system and that can publish SBOMs and VEXes to $somewhere. The process runs under the control of Bombastic or Vexination but can probably share most of the implementation. 

In the first iteration, configuration of auth, certs etc. via command line flags is  sufficient.

Requirements:

* Listen for SBOM/VEX events on Kafka 
* Retrieve SBOM/VEX from s3
* Publish to $endpoint.

**Comment by lulf** [comment]
Relevant: https://quickwit.io/blog/observing-rust-app-with-quickwit-jaeger-grafana

**Comment by lulf** [comment]
Done, @dejanb ?

**Comment by dejanb** [comment]
I think so, at least for the time being ... I think we need to have to reimplement it in Guac directly to avoid big files problem, but let's track that in other issue.
