### ISSUE TITLE
unstable test: spog_dependencies

### ISSUE THREAD

**Issue by lulf** [trustification/trustification#618]
This test fails sporadically. Disabling it for now, but this issue tracks fixing it.

**Comment by lulf** [comment]
This failed in a PR now: https://github.com/trustification/trustification/actions/runs/6652674793/job/18077143561?pr=751

**Comment by jcrossley3** [comment]
> This failed in a PR now: https://github.com/trustification/trustification/actions/runs/6652674793/job/18077143561?pr=751

I can't tell from the logs why. What is the thing that is putting something in guac in response to an SBOM being uploaded? Should its log output be in the CI output?

**Comment by lulf** [comment]
This seems to be failing consistently now:

https://github.com/trustification/trustification/actions/runs/6782340667/job/18434387138
https://github.com/trustification/trustification/actions/runs/6773145184/job/18407327816
https://github.com/trustification/trustification/actions/runs/6745279764/job/18337863557
