### ISSUE TITLE
Searching for UBI SBOMs stopped working

### ISSUE THREAD

**Issue by ctron** [trustification/trustification#665]
Searching for UBI images brings up no results. This worked in the past.

It will use a search term like ` "pkg:oci/redhat/ubi7"`, which now results in an empty set.

**Comment by lulf** [comment]
@ctron I think this is because they change the purls from pkg:oci/redhat/ubi7 to 'pkg:oci/ubi7-container' to be conformant with the package url spec. I'll update the filters
