### ISSUE TITLE
race condition in bombastic_reindexing integration tests

### ISSUE THREAD

**Issue by lulf** [trustification/trustification#692]
After debugging the bombastic_reindexing, it looks like there is a race condition if there are > 1 bombastic API pod running, and I think this is why:

1. Test indexes the test document
2. API pod A pulls down the new index
3. API pod B has not yet pulled down the new index
4. Test queries for the number of hits and the load balancer goes to API pod A which returns 1
5. Test moves into the second part to modify the document and index it again
6. Test queries for the number of hits and the load balancer goes to API pod B which returns 0
7. API pod B pulls down the new index
8. Test fails

The whole issue stems from the fact that the API pods are completely independent and may pull the new index at different points in time.

I will push a fix that resolves this by allowing the second assertion to fail similarly to the first assertion, which should handle the case where the second pod hasn't synced the index yet.

Another, more complex approach, could be to coordinate the index sync between the pods but that would require some coordinator service like etcd/zookeeper or something built into the processes (raft). However, I don't think that API pods being out of sync for a few seconds is that big of an issue.

CC @jcrossley3

**Comment by jcrossley3** [comment]
Nice catch!
