### ISSUE TITLE
Spog correlation test is sensitive to existing documents in index

### ISSUE THREAD

**Issue by lulf** [trustification/trustification#696]
The test may fail if index contains documents already

**Comment by jcrossley3** [comment]
You're getting a little trigger-happy with that `ignore` macro, eh? :smile: 

Can you give me a hint about reproducing it and I'll take a look?

**Comment by lulf** [comment]
To reproduce, I think it suffices to make the test fail once, so that the old documents are there/not cleaned up. And then run it again when it's supposed to succeed.
