### ISSUE TITLE
Disabling dedicated search causes bad links

### ISSUE THREAD

**Issue by lulf** [trustification/trustification#738]
With dedicated search disabled, clicking the following elements will give a 404

<img width="1909" alt="image" src="https://github.com/trustification/trustification/assets/19670/d10cf372-932d-4673-9292-d28a856a002d">

<img width="1909" alt="image" src="https://github.com/trustification/trustification/assets/19670/cd250a24-3477-4a28-bd0d-c661e292fc68">

**Comment by ctron** [comment]
Will be fixed as part of one of my next PRs.

**Comment by mrrajan** [comment]
JIRA issue - https://issues.redhat.com/browse/TC-679
