### ISSUE TITLE
Set security headers for HTTP endpoints

### ISSUE THREAD

**Issue by lulf** [trustification/trustification#780]
* [x] https://infosec.mozilla.org/guidelines/web_security#http-strict-transport-security
* [x] https://infosec.mozilla.org/guidelines/web_security#http-redirections
* [x] https://infosec.mozilla.org/guidelines/web_security#subresource-integrity

**Comment by ctron** [comment]
Just peeking at this: I think the first item should be possible to achieve with an annotation on the `Route`: `haproxy.router.openshift.io/hsts_header: max-age=31536000;includeSubDomains;preload`

The second, we already do?!

The third one is this: https://github.com/thedodd/trunk/issues/583

**Comment by ctron** [comment]
Redirects already work (this is part of the current route configuration):

```
➜  trustification git:(staging) http -v http://staging.trustification.dev/
GET / HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Host: staging.trustification.dev
User-Agent: HTTPie/3.2.1



HTTP/1.1 302 Found
cache-control: no-cache
content-length: 0
location: https://staging.trustification.dev/

```

**Comment by ctron** [comment]
And routes now also default to enabling HSTS (notice the `strict-transport-security: max-age=31536000;includeSubDomains;preload` header in the response):

```
➜  trustification git:(staging) http -v https://staging.trustification.dev/
GET / HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Host: staging.trustification.dev
User-Agent: HTTPie/3.2.1



HTTP/1.1 200 OK
accept-ranges: bytes
cache-control: no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0
content-length: 1527
content-type: text/html
date: Wed, 08 Nov 2023 12:35:15 GMT
etag: "654b7512-5f7"
last-modified: Wed, 08 Nov 2023 11:46:26 GMT
server: nginx/1.20.1
set-cookie: 87f635e2fc4052282a72796bffac5abb=f8e05764ebc1cc2428ae2004b6532339; path=/; HttpOnly; Secure; SameSite=None
strict-transport-security: max-age=31536000;includeSubDomains;preload
```

**Comment by lulf** [comment]
JIRA: https://issues.redhat.com/browse/TC-665
